marks=[]
s1=int(input('enter marks 1 :'))
marks.append(s1)
s2=int(input('enter marks 2 :'))
marks.append(s2)
s3=int(input('enter marks 3 :'))
marks.append(s3)
s4=int(input('enter marks 4 :'))
marks.append(s4)
s5=int(input('enter marks 5 :'))
marks.append(s5)
s6=int(input('enter marks 6 :'))
marks.append(s6)
marks.sort()
print(marks)