s=set()
n= int(input("enter number 1: "))
s.add(n)
n= int(input("enter number 1: "))
s.add(n)
n= int(input("enter number 1: "))
s.add(n)
n= int(input("enter number 1: "))
s.add(n)
n= int(input("enter number 1: "))
s.add(n)
n= int(input("enter number 1: "))
s.add(n)
n= int(input("enter number 1: "))
s.add(n)
n= int(input("enter number 1: "))
s.add(n)
print(s)